import '../models/recipe.dart';

final List<Recipe> kSampleRecipes = [
  Recipe(
    id: '1',
    title: 'Creamy Mushroom Pasta',
    description: 'A delicious and rich pasta dish with sauteed mushrooms in a garlic cream sauce. Perfect for a quick weeknight dinner.',
    imageUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    reviewCount: 124,
    timeInMinutes: 25,
    difficulty: Difficulty.easy,
    category: 'Dinner',
    ingredients: [
      '400g Fettuccine pasta',
      '250g Cremini mushrooms, sliced',
      '2 cloves Garlic, minced',
      '1 cup Heavy cream',
      '1/2 cup Parmesan cheese, grated',
      '2 tbsp Fresh parsley, chopped',
      'Salt and pepper to taste',
      '1 tbsp Olive oil',
    ],
    steps: [
      'Boil a large pot of salted water and cook the pasta according to package instructions until al dente.',
      'Heat olive oil in a large skillet over medium heat. Add mushrooms and sauté until golden brown, about 5-7 minutes.',
      'Add minced garlic and cook for another minute until fragrant.',
      'Pour in the heavy cream and bring to a gentle simmer. Let it thicken slightly for 2-3 minutes.',
      'Stir in the grated Parmesan cheese until melted and smooth.',
      'Drain the pasta and toss it into the sauce. Add parsley, salt, and pepper.',
      'Serve warm with extra Parmesan if desired.',
    ],
  ),
  Recipe(
    id: '2',
    title: 'Grilled Salmon with Asparagus',
    description: 'Fresh salmon fillets grilled to perfection, served with crisp asparagus and a lemon-herb butter sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    reviewCount: 89,
    timeInMinutes: 20,
    difficulty: Difficulty.medium,
    category: 'Lunch',
    ingredients: [
      '2 Salmon fillets',
      '1 bunch Asparagus, trimmed',
      '1 Lemon, sliced',
      '2 tbsp Butter',
      '1 tbsp Fresh dill, chopped',
      'Salt and pepper',
      'Olive oil',
    ],
    steps: [
      'Preheat the grill to medium-high heat.',
      'Toss asparagus with olive oil, salt, and pepper.',
      'Season salmon fillets with salt, pepper, and dill.',
      'Place salmon and asparagus on the grill. Cook salmon for 4-5 minutes per side until flaky.',
      'Grill asparagus for 5-8 minutes until tender-crisp.',
      'Melt butter and mix with a squeeze of lemon juice.',
      'Drizzle lemon butter over salmon and serve immediately.',
    ],
  ),
];
